# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_deps(dep = TRUE)'
  - R -e 'devtools::install()'
after_success:
  - Rscript -e 'covr::codecov()'
